apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
#here is the variables of the ConfigMap
data:
  KEY: VALUE
  DB_Host: HOST_NAME
  DB_User: DB_USER
  DB_password: DB_PASSWORD

#NOTES
#configMaps were create because of managing variables became difficult when they start to grow and unmanagable
#for that reason we create this ConfigMap file and then specify it in the pod definition.

#example in pd-configMap.yaml