apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer #as an example
rules: #we can create as much rules as we can following this example
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "create"]
  resourceNames: ["blue", "default"] #with this we can limit the role to namespaces

- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["list"]