apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin #as an example

rules: #as an array, we can create as much rules as we want.
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "get", "create"]

#NOTES
#after creating this cluster role, we have to create another object called ClusterRoleBinding, you can see the example
#with create-cluster-role-binding.yaml