apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-example
spec:
  backend:
    serviceName: example-service
    servicePort: 80

#NOTES
#this is for controle the ingress traffic. Have to be created with ingress-rules.yaml at the same time