apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-example
spec:
  backend:
    serviceName: example-service
    servicePort: 80

#NOTES
#you have to create something like this if there is no rules. for multipath check ingress-multipath.yaml example