apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-ingress
  template:
    metadata:
      labels:
        name: nginx-ingress #here: ingress-controller-service.yaml
    spec:
      containers:
        - name: nginx-ingress-controller
          image: IMAGE/PATH
      args:
        - /nginx-ingress-controller #the path
        - --configmap=$ (POD_NAMESPACE)/nginx-configuration #here: ingress-controller-configMap.yaml
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443