apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector: #this is very common to use
    app: MyApp
    type: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31234 #range from 30000 - 32767
