apiVersion: v1
kind: Pod
metadata:
  name: POD_NAME

spec:
  containers:
  - name: POD_NAME
    image: IMAGE

    envFrom:
    -  configMapRef:
          name: configMap.metadata.name #here goes the name of the configmap file.