apiVersion: v1
kind: Pod
metadata:
  name: POD_NAME
  labels: #this is what we need to add as a label
    app: APP
    function: Front-End

spec:
  containers:
  - name: POD_NAME
    image: IMAGE
  
  nodeSelector: #this is te selector part
    size: Large

#NOTES
#the selectors are shown in the replicaset-definition.yaml example 
#nodeSelector is used when you label the node, in kubernetes_commands.sh you have the example