apiVersion: v1
kind: Pod
metadata:
  name: POD_NAME

spec:
  containers:
  - name: POD_NAME
    image: IMAGE

  #Container 2 created in the same pod
  - name: POD_NAME_2
    image: IMAGE

#NOTES
#this is used for things like a log agent that have to be attached to the same pod.