apiVersion: v1
kind: Pod
metadata:
  name: POD_NAME

spec:
  containers:
  - name: POD_NAME
    image: IMAGE
  
  #this is for the resource limitations, you can set the limits here
    resources: #inside container
      requests:
        memory: '1Gi'
        cpu: 1
      limits:
        memory: "2Gi"
        cpu: 2