apiVersion: v1
kind: Pod
metadata:
  name: POD_NAME

spec:
  containers:
  - name: POD_NAME
    image: IMAGE

    envFrom:
      - secretRef:
          name: NAME #This name is get from metadata.name of secrets definition file