apiVersion: v1
kind: Pod
metadata:
  name: POD_NAME

spec:
  containers:
  - name: POD_NAME
    image: IMAGE
  
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "Blue"
    effect: "NoSchedule"


#NOTES
#taint nodes not guarantee that the pods with toleration will be as expected.

#A COMBINATION OF TAINTS/TOLERATIONS + NODE AFFINITY IS THE SOLUTION TO FITS THE RESTRICTIONS AND SCHEDULE NEW PODS AS 
#REQUIRED

#effect types:
  #NoSchedule > Kubernetes will not schedule the pod onto that node
  #PreferNoSchedule > Kubernetes will try to not schedule the pod onto the node
  #NoExcute > the pod will be evicted from the node  and not be scheduled onto the node

#operator types:
  #Exists:
  #Equal: is the default.