apiVersion: v1
kind: Pod
metadata:
  name: POD_NAME

spec:
  containers:
  - name: POD_NAME
    image: IMAGE
    #this is the part that belong to ENV variables in Kubernetes
    env:
      - name: "VAR1"
        value: "3"