apiVersion: v1
kind: Pod
metadata:
  name: POD_NAME
  labels: #for labels and selectors
    name: POD_NAME
spec:
  containers:
  - name: POD_NAME
    image: IMAGE
    ports:
      - containerPort: 8080
  
    #this is for multi-container pods. as "containers" is an array yo can add as much as you want, this is an example with name and image
  - name: POD_NAME2
    image: IMAGE
    
    #this is for the resource limitations, you can set the limits here
    resources: #inside container
      requests:
        memory: '1Gi'
        cpu: 1
      limits:
        memory: "2Gi"
        cpu: 2
    
    #this is from the secrets and how to inject them
    envFrom: #inside container
      - secretRef:
          name: NAME_APP_SECRET

  #this is for taints and tolerations
  tolerations: #container level
    - key: "app"
      operator: "Equal"
      value: "VALUE"
      effect: "NoSchedule"
  
  #this is for scheduler, instead of random assign you select in what node it will be deployed.
  nodeName: NODE01 #container level
  
  #this is for labeled nodes, to match with the label of the node
  nodeSelector: #container level
    size: SIZE
  
  #nodeSelector is limited, for that reason nodeAffinity is created
  affinity: #container level
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: size
              operator: in #to select that match the values, or NotIn to not match it, god for Enterprise environments
              values:
                - Large
  